// @audio/synth — synthesis & generators umbrella re-exporting every @audio/synth-* atom.

export { default as noise, white, pink, brown, blue, violet, pinkNoise } from '@audio/synth-noise'
export { default as chirp } from '@audio/synth-chirp'
export { default as osc } from '@audio/synth-osc'
export { default as dtmf } from '@audio/synth-dtmf'
export { default as pluck } from '@audio/synth-pluck'
export { default as risset } from '@audio/synth-risset'
export { default as rhythm } from '@audio/synth-rhythm'
export { default as adsr } from '@audio/synth-envelope'
export { default as lfo } from '@audio/synth-lfo'
export { default as wavetable } from '@audio/synth-wavetable'
export { membrane, metal, noiseDrum } from '@audio/synth-drum'
export { default as fm, bell, epiano } from '@audio/synth-fm'
export { default as modal } from '@audio/synth-modal'
export { default as voice } from '@audio/synth-voice'
export { default as poly } from '@audio/synth-poly'
export { default as sfx, PRESETS as SFX_PRESETS } from '@audio/synth-sfx'
export type { ChirpOptions } from '@audio/synth-chirp'
export type { MembraneOptions, MetalOptions, NoiseDrumOptions } from '@audio/synth-drum'
export type { DtmfOptions } from '@audio/synth-dtmf'
export type { AdsrOptions } from '@audio/synth-envelope'
export type { FmOp, FmOptions } from '@audio/synth-fm'
export type { LfoOptions } from '@audio/synth-lfo'
export type { ModalMode, ModalOptions } from '@audio/synth-modal'
export type { OscOptions } from '@audio/synth-osc'
export type { PluckOptions } from '@audio/synth-pluck'
export type { PolyNote, Voice, PolyOptions } from '@audio/synth-poly'
export type { RhythmOptions } from '@audio/synth-rhythm'
export type { RissetOptions } from '@audio/synth-risset'
export type { SfxPreset, SfxOptions } from '@audio/synth-sfx'
export type { VoiceOptions } from '@audio/synth-voice'
export type { WavetableOptions } from '@audio/synth-wavetable'
