// @audio/synth — synthesis & generators umbrella re-exporting every @audio/synth-* atom.

export { default as pinkNoise } from '@audio/synth-noise'
export { default as noise, white, pink, brown, blue, violet } from '@audio/synth-noise/colors'
export { default as chirp } from '@audio/synth-chirp'
export { default as osc } from '@audio/synth-osc'
export { default as dtmf } from '@audio/synth-dtmf'
export { default as pluck } from '@audio/synth-pluck'
export { default as risset } from '@audio/synth-risset'
export { default as rhythm } from '@audio/synth-rhythm'
export { default as adsr } from '@audio/synth-envelope'
export { default as lfo } from '@audio/synth-lfo'
export { default as wavetable } from '@audio/synth-wavetable'
export { membrane, metal, noiseDrum } from '@audio/synth-drum'
export { default as voice } from '@audio/synth-voice'
